### ISSUE TITLE
Can't import lchmod

### ISSUE THREAD

**Issue by henrykironde** [snakemake/snakemake-interface-common#42]
ImportError: cannot import name 'lchmod' from 'snakemake_interface_common.utils' (MyTools/lib/python3.11/site-packages/snakemake_interface_common/utils.py)

Could this be something that was introduced in the recent new release?

**Comment by johanneskoester** [comment]
This is fixed. It was a missing dependency update because of a premature merge in bioconda-recipes. Thanks for reporting!
